##################################### V 4.3 #####################################


## Run DRVI, DRVI-AP, and scVI for each dataset

### Immune
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/prepared/immune_all_human/adata_hvg.h5ad" --batch "batch@5" --ct final_annotation --plot-keys batch,final_annotation --model drvi scvi --encoder-dims 128,128 --decoder-dims 128,128 --n-latent 32 --n-split-latent 1 MAX --split-aggregation sum logsumexp --split-method split_map --inject-covariates 0 --encode-covariates 0 --decoder-reuse-weights everywhere --cov-model one_hot --gene-likelihood pnb_softmax --batch-norm none --layer-norm both --activation-fn elu --encoder-dropout 0.1
### Developmental pancreas
python drvi_runvis.py --seed $RANDOM -e 1000 -i "/home/icb/amirali.moinfar/data/developmental/pancreas_scvelo_hvg.h5ad" --lognorm-layer scvelo_normalized --count-layer counts --batch "" --ct clusters_coarse --plot-keys clusters_coarse,clusters,latent_time --model scvi drvi --encoder-dims 128 --decoder-dims 128 --n-latent 32 --n-split-latent 1 MAX --split-aggregation sum logsumexp --split-method split_map --cov-model one_hot --gene-likelihood pnb_softmax --decoder-reuse-weights everywhere --batch-norm none --layer-norm both  --activation-fn elu --encoder-dropout 0.1
### CRISPR screen
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/pertpy/norman_2019_hvg.h5ad" --batch "" --lognorm-layer X  --count-layer counts --ct perturbation_name --model scvi drvi --plot-keys group_BAK1_TMSB4X --encoder-dims 512,512,512 --decoder-dims 512,512,512 --n-latent 64 --n-split-latent 1 MAX --split-aggregation sum logsumexp --split-method split_map --gene-likelihood pnb_softmax --decoder-reuse-weights everywhere --batch-norm none --layer-norm both --activation-fn elu  --target-kl 1.
### Retina organoid
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/retina_adult_organoid/retina_organoid_hvg.h5ad" --batch "sample_id@5" --ct cell_type --plot-keys cell_type,source --model drvi scvi --encoder-dims 128 --decoder-dims 128 --n-latent 32 --n-split-latent 1 MAX --split-aggregation sum logsumexp --split-method split_map --inject-covariates 0 --encode-covariates 0 --decoder-reuse-weights everywhere --cov-model one_hot --gene-likelihood pnb_softmax --batch-norm none --layer-norm both --activation-fn elu --encoder-dropout 0.1
### PBMC
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/pbmc/haniffa21_rna_hvg.h5ad" --lognorm-layer X --count-layer counts --batch Site@5 --ct full_clustering --plot-keys Site,full_clustering --model scvi drvi --encoder-dims 256,256 --n-latent 64 --n-split-latent 1 MAX --split-aggregation sum logsumexp --split-method split_map --decoder-reuse-weights everywhere --cov-model one_hot --gene-likelihood pnb_softmax --batch-norm none --layer-norm both --activation-fn elu --encode-covariates 0 --encoder-dropout 0.1
### HLCA
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/HLCA/hlca_core_hvg.h5ad" --lognorm-layer X --count-layer counts --batch sample@20 --ct ann_finest_level --plot-keys dataset,ann_finest_level --model scvi drvi --encoder-dims 256,256 --n-latent 64 --n-split-latent 1 MAX --split-aggregation sum logsumexp --split-method split_map --decoder-reuse-weights everywhere --cov-model one_hot --gene-likelihood pnb_softmax --batch-norm none --layer-norm both --activation-fn elu --encode-covariates 0 --encoder-dropout 0.1
### Daniocell
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/zebrafish/zebrafish_processed_v1_hvg_2000.h5ad" --lognorm-layer X --count-layer counts --batch "" --ct "tissue.name" --plot-keys "tissue.name,stage.group" --model scvi drvi --encoder-dims 256,256 --decoder-dims 256,256 --n-latent 64 --n-split-latent 1 MAX --split-aggregation sum logsumexp --split-method split --cov-model one_hot --gene-likelihood pnb_softmax --decoder-reuse-weights last everywhere --batch-norm none --layer-norm both  --activation-fn elu --encoder-dropout 0.1
### NeuroIPS21 - scATAC
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/nips_21_multiome/atac_modality_hvg.h5ad" --lognorm-layer X --count-layer fragments --batch batch@20 --ct neurips21_cell_type --plot-keys batch,neurips21_cell_type --model poissonvi peakvi drvi --encoder-dims 256,256 --n-latent 64 --n-split-latent 1 MAX --split-aggregation sum logsumexp --split-method split_map --decoder-reuse-weights everywhere --cov-model one_hot --gene-likelihood poisson_orig --batch-norm none --layer-norm both --activation-fn elu --encode-covariates 0 --encoder-dropout 0.1




## Ablation study on the number of latent dimensions

### Immune with all genes
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/prepared/immune_all_human/immune_all_genes.h5ad" --batch "batch@5" --ct final_annotation --plot-keys batch,final_annotation --model drvi scvi --encoder-dims 512,512 --decoder-dims 512,512 --n-latent 2 4 6 8 10 12 14 16 32 64 128 256 512 1024 2048 --n-split-latent MAX --split-aggregation logsumexp --split-method split_map --inject-covariates 0 --encode-covariates 0 --decoder-reuse-weights everywhere --cov-model one_hot --gene-likelihood pnb_softmax --batch-norm none --layer-norm both --activation-fn elu --encoder-dropout 0.1
### Immune with highly variable genes
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/prepared/immune_all_human/adata_hvg.h5ad" --batch "batch@5" --ct final_annotation --plot-keys batch,final_annotation --model scvi drvi --encoder-dims 128,128 --decoder-dims 128,128 --n-latent 2 4 6 8 10 12 14 16 32 64 128 256 512 --n-split-latent MAX --split-aggregation logsumexp --split-method split_map --inject-covariates 0 --encode-covariates 0 --decoder-reuse-weights everywhere --cov-model one_hot --gene-likelihood pnb_softmax --batch-norm none --layer-norm both --activation-fn elu --encoder-dropout 0.1
### Developmental pancreas
python drvi_runvis.py --seed $RANDOM -e 1000 -i "/home/icb/amirali.moinfar/data/developmental/pancreas_scvelo_hvg.h5ad" --lognorm-layer scvelo_normalized --count-layer counts --batch "" --ct clusters_coarse --plot-keys clusters_coarse,clusters,latent_time --model drvi --encoder-dims 128 --decoder-dims 128 --n-latent 32 64 128 256 512 --n-split-latent MAX --split-aggregation logsumexp --split-method split --cov-model one_hot --gene-likelihood pnb_softmax --decoder-reuse-weights last --batch-norm none --layer-norm both  --activation-fn elu --encoder-dropout 0.1
### CRISPR screen
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/pertpy/norman_2019_hvg.h5ad" --batch "" --lognorm-layer X  --count-layer counts --ct perturbation_name --model drvi --plot-keys group_BAK1_TMSB4X --encoder-dims 512,512,512 --decoder-dims 512,512,512 --n-latent 32 64 128 256 512 --n-split-latent MAX --split-aggregation logsumexp --split-method split_map --gene-likelihood pnb_softmax --decoder-reuse-weights everywhere --batch-norm none --layer-norm both --activation-fn elu  --target-kl 1.
### Retina organoid
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/retina_adult_organoid/retina_organoid_hvg.h5ad" --batch "sample_id@5" --ct cell_type --plot-keys cell_type,source --model drvi --encoder-dims 128 --decoder-dims 128 --n-latent 32 64 128 256 512 --n-split-latent MAX --split-aggregation logsumexp --split-method split_map --inject-covariates 0 --encode-covariates 0 --decoder-reuse-weights everywhere --cov-model one_hot --gene-likelihood pnb_softmax --batch-norm none --layer-norm both --activation-fn elu --encoder-dropout 0.1
### PBMC
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/pbmc/haniffa21_rna_hvg.h5ad" --lognorm-layer X --count-layer counts --batch Site@5 sample_id@20 --ct full_clustering --plot-keys Site,full_clustering --model drvi --encoder-dims 256,256 --n-latent 32 64 128 256 512 --n-split-latent MAX --split-aggregation logsumexp --split-method split_map --decoder-reuse-weights everywhere --cov-model one_hot --gene-likelihood pnb_softmax --batch-norm none --layer-norm both --activation-fn elu --encode-covariates 0 --encoder-dropout 0.1
### HLCA
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/HLCA/hlca_core_hvg.h5ad" --lognorm-layer X --count-layer counts --batch sample@20 --ct ann_finest_level --plot-keys dataset,ann_finest_level --model drvi --encoder-dims 256,256 --n-latent 32 64 128 256 512 1024 2048 --n-split-latent MAX --split-aggregation logsumexp --split-method split_map --decoder-reuse-weights everywhere --cov-model one_hot --gene-likelihood pnb_softmax --batch-norm none --layer-norm both --activation-fn elu --encode-covariates 0 --encoder-dropout 0.1
### Daniocell
python drvi_runvis.py --seed $RANDOM -e 400 -i "/home/icb/amirali.moinfar/data/zebrafish/zebrafish_processed_v1_hvg_2000.h5ad" --lognorm-layer X --count-layer counts --batch "" --ct "tissue.name" --plot-keys "tissue.name,stage.group" --model drvi --encoder-dims 256,256 --decoder-dims 256,256 --n-latent 32 64 128 256 512 1024 2048 --n-split-latent MAX --split-aggregation logsumexp --split-method split --cov-model one_hot --gene-likelihood pnb_softmax --decoder-reuse-weights last everywhere --batch-norm none --layer-norm both  --activation-fn elu --encoder-dropout 0.1

